name: Main

on:
  push:
    branches: 
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Create new tag
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # Generate a timestamp-based tag
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token to interact with GitHub API
