name: Build, Test and Release

on:
  push:
    branches:
      - master  # Trigger on push to the master branch

jobs:

  release:
    runs-on: ubuntu-latest  # Run the release on a separate runner
    if: github.ref == 'refs/heads/master'  # Only trigger on the master branch push

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    # Step 2: Get the latest tag from git and increment it
    - name: Get current version tag and increment
      id: tag_version
      run: |
        # Use 'git describe' to reliably get the latest tag
        latest_tag=$(git describe --tags --abbrev=0)
        echo "latest_tag=$latest_tag"
        if [[ -z "$latest_tag" ]]; then
          new_tag="v1.0.0"  # If no tags exist, start with v1.0.0
        else
          # Increment the patch version properly
          IFS='.' read -r major minor patch <<< "${latest_tag//v/}"  # Remove 'v' and split into components
          ((patch++))  # Increment the patch version
          new_tag="v$major.$minor.$patch"  # Reassemble the version string
        fi
        echo "new_tag=$new_tag" >> $GITHUB_ENV

    # Step 3: Configure git to use GitHub token for authentication
    - name: Configure git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
    # Step 4: Create the new tag
    - name: Create new Git tag
      run: |
        git tag ${{ env.new_tag }}

    # Step 5: Push the tag to the repository using GITHUB_TOKEN for authentication
    - name: Push new tag
      run: |
        git push https://github.com/${{ github.repository }} ${{ env.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Step 6: Create a GitHub release
    - name: Create GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.new_tag }}
        release_name: Release ${{ env.new_tag }}
        body: |
          New release for version ${{ env.new_tag }}.
